"""Distance-aware static KV-retention pattern learning."""

from .training.data_pipeline.contracts import validate_tokenizer_contract
from .training.data_pipeline.coverage import CoverageGroup, build_coverage_groups, validate_coverage
from .training.data_pipeline.dataset import (
    IndependentQueryBranchExample,
    IndependentQueryDataset,
    IndependentQueryDatasetCollection,
    IndependentQueryTrainingExample,
    ManifestDataset,
    PatternTrainingExample,
    single_example_collate,
    single_independent_example_collate,
)
from .training.pattern_learning.distributed_training import (
    ContextShard,
    backward_distributed_q_head_branches,
    build_context_shards,
    context_offsets_for_rank,
    ddp_task_loss_scale,
    unwrap_q_head_gates,
)
from .training.pattern_learning.gated_attention import (
    GatedAttentionOutput,
    build_prompt_block_gate,
    grouped_block_gated_attention,
    kv_head_block_gated_attention,
    q_head_block_gated_attention,
)
from .training.audits.gradient_audit import (
    DEFAULT_CONTEXT_CHECKPOINTS,
    GradientSnapshot,
    calibrate_gatewise_l0,
    calibrate_l0_coefficients,
    compare_gradient_snapshot,
    manifest_distance_coverage,
    q_head_gate_sample_seed,
    resolve_context_checkpoints,
)
from .training.pattern_learning.hard_concrete import (
    HardConcreteConfig,
    HardConcreteEndpointMass,
    HardConcreteGates,
    HardConcreteSample,
    KVHeadHardConcreteGates,
    QHeadHardConcreteGates,
    hard_concrete_log_alpha_from_keep_probability,
)
from .core.layout import BlockLayout
from .inference.static_q_head.llama2_q_head_inference import (
    Llama2QHeadCache,
    install_llama2_q_head_attention,
)
from .inference.static_q_head.llama31_q_head_inference import (
    Llama31QHeadCache,
    install_llama31_q_head_attention,
)
from .core.log_progress import LogProgressBar
from .training.data_pipeline.manifest import (
    ManifestPlanner,
    NeedlePlan,
    SamplePlan,
    read_manifest,
    validate_plans,
    write_manifest,
)
from .training.data_pipeline.materialize import (
    IndependentMaterializedSample,
    IndependentQuerySuffix,
    InstructMaterializer,
    MaterializedSample,
    ValueTokenSpan,
)
from .training.pattern_learning.q_head_trainer import (
    FORMAL_CONTEXTS_PER_OPTIMIZER_STEP,
    FORMAL_L0_LAMBDA,
    FORMAL_L0_RAMP_STEPS,
    FORMAL_L0_START_STEP,
    FORMAL_LEARNING_RATE,
    FORMAL_MAX_OPTIMIZER_STEPS,
    FORMAL_MILESTONE_STEPS,
    ContextOccurrence,
    QHeadTrainingHyperparameters,
    context_occurrences_for_step,
    exact_topk_mask,
    formal_manifest_collection_id,
    formal_manifest_id,
    manifest_group_index_for_step,
    normalized_step_branch_weights,
    planned_gate_indices,
    q_head_training_gate_sample_seed,
    resolve_milestone_steps,
    resolve_optimizer_step_run_limit,
    scheduled_l0_coefficient,
    st_topk_keep_ratio_for_context,
    validate_continuation_checkpoint,
)
from .training.retrieval_initialization.retrieval_init import load_retrieval_head_scores
from .training.pattern_learning.runner_types import (
    GatedBranchesOutput,
    GatedSuffixOutput,
    PromptKVCache,
    QHeadSuffixRunner,
    causal_value_cross_entropy,
)
from .training.data_pipeline.templates import (
    ALL_TEMPLATE_IDS,
    HELDOUT_TEMPLATE_IDS,
    TRAIN_TEMPLATE_IDS,
    VALUE_TYPES,
)
from .training.pattern_learning.training_step import (
    BranchwiseBackwardResult,
    QHeadGateInitialization,
    backward_independent_q_head_branches,
    distance_balanced_branch_weights,
    gradient_competition_statistics,
    initialize_q_head_gates_from_retrieval,
    l0_candidate_first_step_statistics,
    polarization_candidate_continuation_statistics,
    retrieval_scores_to_keep_probability,
)

__all__ = [
    "ALL_TEMPLATE_IDS",
    "DEFAULT_CONTEXT_CHECKPOINTS",
    "FORMAL_CONTEXTS_PER_OPTIMIZER_STEP",
    "FORMAL_L0_LAMBDA",
    "FORMAL_L0_RAMP_STEPS",
    "FORMAL_L0_START_STEP",
    "FORMAL_LEARNING_RATE",
    "FORMAL_MAX_OPTIMIZER_STEPS",
    "FORMAL_MILESTONE_STEPS",
    "HELDOUT_TEMPLATE_IDS",
    "TRAIN_TEMPLATE_IDS",
    "VALUE_TYPES",
    "BlockLayout",
    "BranchwiseBackwardResult",
    "ContextOccurrence",
    "ContextShard",
    "CoverageGroup",
    "GatedAttentionOutput",
    "GatedBranchesOutput",
    "GatedSuffixOutput",
    "GradientSnapshot",
    "HardConcreteConfig",
    "HardConcreteEndpointMass",
    "HardConcreteGates",
    "HardConcreteSample",
    "IndependentMaterializedSample",
    "IndependentQueryBranchExample",
    "IndependentQueryDataset",
    "IndependentQueryDatasetCollection",
    "IndependentQuerySuffix",
    "IndependentQueryTrainingExample",
    "InstructMaterializer",
    "KVHeadHardConcreteGates",
    "Llama2QHeadCache",
    "Llama31QHeadCache",
    "LogProgressBar",
    "ManifestDataset",
    "ManifestPlanner",
    "MaterializedSample",
    "NeedlePlan",
    "PatternTrainingExample",
    "PromptKVCache",
    "QHeadGateInitialization",
    "QHeadSuffixRunner",
    "QHeadHardConcreteGates",
    "QHeadTrainingHyperparameters",
    "SamplePlan",
    "ValueTokenSpan",
    "backward_distributed_q_head_branches",
    "backward_independent_q_head_branches",
    "build_context_shards",
    "build_coverage_groups",
    "build_prompt_block_gate",
    "calibrate_gatewise_l0",
    "calibrate_l0_coefficients",
    "causal_value_cross_entropy",
    "compare_gradient_snapshot",
    "context_occurrences_for_step",
    "context_offsets_for_rank",
    "ddp_task_loss_scale",
    "distance_balanced_branch_weights",
    "exact_topk_mask",
    "formal_manifest_collection_id",
    "formal_manifest_id",
    "gradient_competition_statistics",
    "grouped_block_gated_attention",
    "hard_concrete_log_alpha_from_keep_probability",
    "initialize_q_head_gates_from_retrieval",
    "install_llama2_q_head_attention",
    "install_llama31_q_head_attention",
    "kv_head_block_gated_attention",
    "l0_candidate_first_step_statistics",
    "load_retrieval_head_scores",
    "manifest_distance_coverage",
    "manifest_group_index_for_step",
    "normalized_step_branch_weights",
    "planned_gate_indices",
    "polarization_candidate_continuation_statistics",
    "q_head_block_gated_attention",
    "q_head_gate_sample_seed",
    "q_head_training_gate_sample_seed",
    "read_manifest",
    "resolve_context_checkpoints",
    "resolve_milestone_steps",
    "resolve_optimizer_step_run_limit",
    "retrieval_scores_to_keep_probability",
    "scheduled_l0_coefficient",
    "single_example_collate",
    "single_independent_example_collate",
    "st_topk_keep_ratio_for_context",
    "unwrap_q_head_gates",
    "validate_continuation_checkpoint",
    "validate_coverage",
    "validate_plans",
    "validate_tokenizer_contract",
    "write_manifest",
]
